version: '3'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
  web:
    build: ./dockerfiles/web/
    tty: true
    volumes:
      - myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  dbdata:
  myapp: